---
- name: Infrastructure Tools
  hosts: all
  vars_files:
  - settings.yml
  tasks:
  - name: Update kubeconfig for cluster
    community.digitalocean.digital_ocean_kubernetes_info:
      oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
      name: alleaffengaffen
      return_kubeconfig: yes
    register: alleaffengaffen
  - name: Cluster information
    debug:
      msg:
        - "Cluster name is {{ alleaffengaffen.data.name }}, ID is {{ alleaffengaffen.data.id }}"
        - "Cluster kubeconfig is {{ alleaffengaffen.data.kubeconfig }}"
  post_tasks:
    - name: We are ready
      debug:
        msg:
          - "Kubernetes cluster is provisioned and tools are installed"
