---
- name: Infrastructure Tools
  hosts: localhost
  vars_files:
  - settings.yml
  tasks:
  - name: Update kubeconfig for cluster
    community.digitalocean.digital_ocean_kubernetes_info:
      oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
      name: alleaffengaffen
      return_kubeconfig: yes
    register: alleaffengaffen
  - name: Cluster information
    debug:
      msg:
        - "Cluster name is {{ alleaffengaffen.data.name }}, ID is {{ alleaffengaffen.data.id }}"
        - "Cluster kubeconfig is {{ alleaffengaffen.data.kubeconfig }}"
  - name: Deploy external-dns helm chart
    kubernetes.core.helm:
      kubeconfig: "{{ alleaffengaffen.data.kubeconfig }}"
      chart_repo_url: "https://kubernetes-sigs.github.io/external-dns/"
      chart_ref: external-dns
      chart_version: 1.7.1
      release_name: external-dns
      release_namespace: external-dns
      release_values: "{{ lookup('template', 'values/external-dns.yaml') | from_yaml }}"
  post_tasks:
    - name: We are ready
      debug:
        msg:
          - "Kubernetes cluster is provisioned and tools are installed"
