---
- name: Infrastructure Tools
  hosts: localhost
  vars:
    domainFilters: ['alleaffengaffen.ch'] # Domains external-dns shall manage
    txtOwnerId: 'alleaffengaffen' # Owner to note in TXT records
    cluster_name: 'alleaffengaffen'
    kubeconfig_path: '$HOME/kubeconfig' # location to write kubeconfig to (dir needs to exist)
    do_api_token: '' # override with ansible_vault file
  tasks:
  - name: Update kubeconfig for cluster
    community.digitalocean.digital_ocean_kubernetes_info:
      oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
      name: "{{ cluster_name }}"
      return_kubeconfig: yes
    register: doks
  - name: Write kubeconfig to file
    copy:
      content: "{{ doks.data.kubeconfig | to_nice_yaml }}"
      dest: "{{ kubeconfig_path }}"
      mode: 0600
  - name: Deploy external-dns helm chart
    kubernetes.core.helm:
      kubeconfig_path: "{{ kubeconfig_path }}"
      chart_repo_url: "https://kubernetes-sigs.github.io/external-dns/"
      chart_ref: external-dns
      chart_version: 1.7.1
      release_name: external-dns
      release_namespace: external-dns
      release_values: "{{ lookup('template', 'values/external-dns.yaml') | from_yaml }}"
  post_tasks:
    - name: We are ready
      debug:
        msg:
          - "Kubernetes cluster is provisioned and tools are installed"
